crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crudApp/', include('crudApp.urls') )
]

crud/crudApp/urls.py
from django.urls import path 
from .views import home, student_edit, student_delete, account_login,account_signup

urlpatterns = [
    path('', account_login, name='account_login'),
    path('signup/', account_signup, name='account_signup'),
    path('home/', home, name='home'),
    path('std/<int:pk>/edit/', student_edit, name='student_edit'),
    path('std/<int:pk>/delete/', student_delete, name='student_delete'),
]

crud/crudApp/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    stdName = models.CharField(max_length=255)
    stdAge = models.CharField(max_length=100)
    stdCourse = models.CharField(max_length=100)

class Account(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField()
    password= models.CharField(max_length=255)
    birthdate = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name
    

   

crud/crudApp/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.hashers import check_password
from .models import Student,Account

# Create your views here.
def account_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            
            account = Account.objects.get(username=username)
        except Account.DoesNotExist:
            account = None

        if account and password== account.password:
            return redirect('home') 

    return render(request, 'login.html')    

def account_signup(request):
    if request.method =="POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        date = request.POST.get('date')
        password = request.POST.get('password')

        account = Account.objects.create(username=username, email=email, birthdate=date, password=password)
        account.save()
        return redirect(account_login)

    return render(request, 'signup.html') 

def home(request):
    students = Student.objects.all()
    if request.method == "POST":
        std_name = request.POST.get('stdName')
        std_age = request.POST.get('stdAge')
        std_course = request.POST.get('stdCourse')

        student = Student.objects.create(stdName=std_name, stdAge=std_age, stdCourse=std_course)
        student.save()
    
    return render(request, 'index.html', {'students':students})

# updating 
def student_edit(request, pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == "POST":
        student.stdName = request.POST.get('stdName')
        student.stdAge = request.POST.get('stdAge')
        student.stdCourse = request.POST.get('stdCourse')
        student.save()
        return redirect(home)
    return render(request, 'pages/student-edit.html', {'std' : student})

def student_delete(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student.delete()
    return redirect(home)

crud/crudApp/templates/index.html
{% extends 'layout.html'%}

{%block content%}

<div class="container p-3">
    <div class="row">
        <div class="col-md-3">
            <h4 class="text-center">Add Student</h4>
            <form method="post" action="{% url 'home' %}" class="form-group">
                {% csrf_token %}

                <label for="id_stdName">Name:</label>
                <input type="text" name="stdName" id="id_stdName" class="form-control">
                <br>

                <label for="id_stdAge">Age:</label>
                <input type="text" name="stdAge" id="id_stdAge" class="form-control">
                <br>

                <label for="id_stdCourse">Course:</label>
                <input type="text" name="stdCourse" id="id_stdCourse" class="form-control">
                <br>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>

        </div>
        <div class="col-md-9">
            <h4 class="text-center">Students</h4>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Age</th>
                        <th>Course</th>
                        <th>Action</th>
                    </tr>
                <tbody>
                    {%for std in students %}
                    <tr>
                        <td>{{std.stdName}}</td>
                        <td>{{std.stdAge}}</td>
                        <td>{{std.stdCourse}}</td>
                        <td>
                            <a href="{% url 'student_edit' pk=std.id %}" class="btn btn-warning">Edit</a>
                            <a href="{% url 'student_delete' pk=std.id %} "
                                onclick="return confirm('Are you sure you want to delete {{ std.stdName }}?')"
                                class="btn btn-danger">Delete</a>

                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
                </thead>
            </table>

        </div>
    </div>
</div>
{%endblock%}

crud/crudApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django MVC project by Shaka</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

{%block content%}
{%endblock%}
<body>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>

</body>

</html>

crud/crudApp/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="w-75 mx-auto">

        <h2>Login</h2>
        <form method="post" action="{% url 'account_login' %}" class="form-group">
            {% csrf_token %}

            <label for="id_user">Username:</label>
            <input type="text" name="username" id="id_username" required class="form-control my-2">

            <label for="id_password">Password:</label>
            <input type="password" name="password" id="id_password" required class="form-control my-2">

            <button class="btn btn-primary" type="submit">Login</button>

        </form>
        <a href="{%url 'account_signup'%}" class="text-center nav-link">Don't Have an account? Create One</a>
    </div>
</div>

{% endblock %}

crud/crudApp/templates/pages/student-edit.html
{%extends 'layout.html'%}

{%block content%}
<div class="container">
    <div class="w-75 mx-auto">
        <h1>Edit Student</h1>
        <form method="post" action="{% url 'student_edit' pk=std.id %}" class="form-group">
            {% csrf_token %}

            <label for="id_stdName">Name:</label>
            <input type="text" name="stdName" id="id_stdName" class="form-control" value="{{ std.stdName }}">
            <br>

            <label for="id_stdAge">Age:</label>
            <input type="text" name="stdAge" id="id_stdAge" class="form-control" value="{{ std.stdAge }}">
            <br>

            <label for="id_stdCourse">Course:</label>
            <input type="text" name="stdCourse" id="id_stdCourse" class="form-control" value="{{ std.stdCourse }}">
            <br>

            <button type="submit" class="btn btn-warning">Update</button>
    </div>
</div>
{%endblock%}

crud/crudApp/templates/signup.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="w-75 mx-auto">
        <h2 class="text-center">Create Account</h2>
        <form method="post" action="{% url 'account_signup' %}" class="form-group">
            {% csrf_token %}

            <label for="id_username">Username:</label>
            <input type="text" name="username" id="id_username" required class="form-control my-1">

            <label for="id_email">Email:</label>
            <input type="email" name="email" id="id_email" required class="form-control my-1">

            <label for="id_date">Date of Birth:</label>
            <input type="date" name="date" id="id_date" required class="form-control my-1">

            <label for="id_password">Password:</label>
            <input type="password" name="password" id="id_password" required class="form-control my-1">

            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <a href="{%url 'account_login'%}" class="text-center nav-link">Already Have an account? Login</a>
    </div>
</div>

{% endblock %}